# Generated by Django 5.0.6 on 2024-05-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='nome',
            new_name='Nome',
        ),
    ]
